kind: pipeline
type: docker
name: default

steps:
- name: test
  image: golang
  commands:
  - go test
  - go build

- name: docker
  image: plugins/docker
  settings:
    username:
      from_secret: docker_username
    password:
      from_secret: docker_password
    repo: snake1597/go_webserver
    tags: latest
